version: '2'
services:
  dhi_alumni-app:
    image: dhi_alumni
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://dhi_alumni-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=dhi_alumni
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  dhi_alumni-mongodb:
    extends:
      file: mongodb.yml
      service: dhi_alumni-mongodb
